services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: multiplanner
      POSTGRES_USER: multiplanner
      POSTGRES_PASSWORD: multiplanner
    ports:
      - "5432:5432"
    volumes:
      # Persist DB data
      - pgdata:/var/lib/postgresql/data

      # Make CSV visible to Postgres 
      - ./data/naptan:/data/naptan:ro

      # Run SQL on first init only 
      - ./sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7

  backend:
    build:
      context: ../backend
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/multiplanner
      SPRING_DATASOURCE_USERNAME: multiplanner
      SPRING_DATASOURCE_PASSWORD: multiplanner
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    ports:
      - "8080:80"   

volumes:
  pgdata:

