server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multiplanner
    username: multiplanner
    password: multiplanner
    driver-class-name: org.postgresql.Driver
  
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes in ms

tfl:
  base-url: https://api.tfl.gov.uk
  app-key: ${TFL_APP_KEY:}
