server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multiplanner
    username: multiplanner
    password: multiplanner
    driver-class-name: org.postgresql.Driver

tfl:
  base-url: https://api.tfl.gov.uk
  app-key: ${TFL_APP_KEY:}
